include: package:lints/recommended.yaml

analyzer:
  errors:
    strict_raw_type: ignore
  language:
    strict-casts: true 
    strict-inference: true
    strict-raw-types: true


linter:
  rules:
    avoid_print: true
    library_prefixes: false
    avoid_relative_lib_imports: true
    avoid_types_as_parameter_names: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    unawaited_futures: true 
    always_put_required_named_parameters_first: true
    await_only_futures: true
    
