name: your_tracker
description: Your app of tracker brazilian packages

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_modular: ^6.3.2
  lottie: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
        - asset: assets/fonts/Ubuntu-Medium.ttf
        - asset: assets/fonts/Ubuntu-Regular.ttf
